# Generated by Django 4.2 on 2024-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('citizen_id', models.CharField(max_length=18)),
                ('student_id', models.CharField(max_length=19)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
