# Generated by Django 4.2 on 2024-05-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='student_info',
        ),
    ]
