# Generated by Django 4.2 on 2024-05-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_student_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='id',
        ),
        migrations.AddField(
            model_name='student_info',
            name='in_class',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student_info',
            name='school',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student_info',
            name='sex',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
