# Generated by Django 4.2 on 2024-05-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_info_id_student_info_in_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='password',
            field=models.CharField(default='123456', max_length=18),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='citizen_id',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_id',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
