# Generated by Django 4.2 on 2024-06-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_info_password_alter_student_info_citizen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='password',
            field=models.CharField(default='', max_length=18),
        ),
    ]
